// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Color;

  Color = (function() {
    Color.prototype.r = 0;

    Color.prototype.g = 0;

    Color.prototype.b = 0;

    Color.prototype.a = 0;

    function Color(r, g, b, a) {
      this.r = r != null ? r : 0;
      this.g = g != null ? g : 0;
      this.b = b != null ? b : 0;
      this.a = a != null ? a : 0;
    }

    Color.create = function(r, g, b, a) {
      return new Color(r, g, b, a);
    };

    return Color;

  })();
  Color.prototype.Transparent = new Color(0, 0, 0, 0);
  Color.prototype.None = new Color(0, 0, 0, 0);
  Color.prototype.Black = new Color(0, 0, 0, 1);
  Color.prototype.White = new Color(1, 1, 1, 1);
  Color.prototype.Grey = new Color(0.5, 0.5, 0.5, 1);
  Color.prototype.Red = new Color(1, 0, 0, 1);
  Color.prototype.Green = new Color(0, 1, 0, 1);
  Color.prototype.Blue = new Color(0, 0, 1, 1);
  Color.prototype.Yellow = new Color(1, 1, 0, 1);
  Color.prototype.Pink = new Color(1, 0, 1, 1);
  Color.prototype.Cyan = new Color(0, 1, 1, 1);
  Color.prototype.Orange = new Color(1, 0.5, 0, 1);
  return Color;
});
