// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Edge;

  return Edge = (function() {
    function Edge(a, b) {
      this.a = a;
      this.b = b;
    }

    return Edge;

  })();
});
