// Generated by CoffeeScript 1.7.1
define(function(require) {
  var Edge;
  return Edge = (function() {
    function Edge(a, b) {
      this.a = a;
      this.b = b;
    }

    return Edge;

  })();
});
