// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Geometry, elementSizeMap;

  elementSizeMap = {
    'Vec2': 2,
    'Vec3': 3,
    'Vec4': 4
  };
  return Geometry = (function() {
    function Geometry(attribs) {
      var attrib, attribName, _ref, _ref1;

      this.faces = [];
      this.edges = [];
      this.attribs = attribs || {};
      _ref = this.attribs;
      for (attribName in _ref) {
        attrib = _ref[attribName];
        attrib.isDirty = true;
        attrib.elementSize = elementSizeMap[attrib.type];
        attrib.data = [];
        attrib.length = (_ref1 = attrib.length) != null ? _ref1 : 0;
        attrib.buf = new Float32Array(attrib.elementSize * attrib.length);
      }
    }

    return Geometry;

  })();
});
