// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Line2D, Vec2;

  Vec2 = require('pex/geom/Vec2');
  return Line2D = (function() {
    function Line2D(a, b) {
      this.a = a;
      this.b = b;
    }

    Line2D.prototype.isPointOnTheLeftSide = function(p) {
      return ((this.b.x - this.a.x) * (p.y - this.a.y) - (this.b.y - this.a.y) * (p.x - this.a.x)) <= 0;
    };

    Line2D.prototype.projectPoint = function(p) {
      var ab, ap, d;

      ab = Vec2.create().asSub(this.b, this.a).normalize();
      ap = Vec2.create().asSub(p, this.a);
      d = ab.dot(ap);
      return ab.scale(d).add(this.a);
    };

    Line2D.prototype.distanceToPoint = function(p) {
      return this.projectPoint(p).distance(p);
    };

    return Line2D;

  })();
});
