// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Vec4;

  return Vec4 = (function() {
    Vec4.prototype.x = 0;

    Vec4.prototype.y = 0;

    Vec4.prototype.z = 0;

    Vec4.prototype.w = 0;

    function Vec4(x, y, z, w) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
      this.z = z != null ? z : 0;
      this.w = w != null ? w : 0;
    }

    Vec4.create = function(x, y, z, w) {
      return new Vec4(x, y, z, w);
    };

    return Vec4;

  })();
});
