// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Vec4;

  return Vec4 = (function() {
    Vec4.prototype.x = 0;

    Vec4.prototype.y = 0;

    Vec4.prototype.z = 0;

    Vec4.prototype.w = 0;

    function Vec4(x, y, z, w) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
      this.z = z != null ? z : 0;
      this.w = w != null ? w : 0;
    }

    Vec4.create = function(x, y, z, w) {
      return new Vec4(x, y, z, w);
    };

    Vec4.prototype.set = function(x, y, z, w) {
      this.x = x;
      this.y = y;
      this.z = z;
      this.w = w;
      return this;
    };

    Vec4.prototype.transformMat4 = function(m) {
      var w, x, y, z;

      x = m.a14 * this.w + m.a11 * this.x + m.a12 * this.y + m.a13 * this.z;
      y = m.a24 * this.w + m.a21 * this.x + m.a22 * this.y + m.a23 * this.z;
      z = m.a34 * this.w + m.a31 * this.x + m.a32 * this.y + m.a33 * this.z;
      w = m.a44 * this.w + m.a41 * this.x + m.a42 * this.y + m.a43 * this.z;
      this.x = x;
      this.y = y;
      this.z = z;
      this.w = w;
      return this;
    };

    return Vec4;

  })();
});
