// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Camera, Mat4, Vec3, _ref;

  _ref = require('pex/geom'), Vec3 = _ref.Vec3, Mat4 = _ref.Mat4;
  return Camera = (function() {
    function Camera(fov, aspectRatio, near, far, position, target, up) {
      this.fov = fov || 60;
      this.aspectRatio = aspectRatio || 4 / 3;
      this.near = near || 0.1;
      this.far = far || 100;
      this.position = position || Vec3.create(0, 0, 5);
      this.target = target || Vec3.create(0, 0, 0);
      this.up = up || Vec3.create(0, 1, 0);
      this.projectionMatrix = Mat4.create();
      this.viewMatrix = Mat4.create();
      this.updateMatrices();
    }

    Camera.prototype.updateMatrices = function() {
      this.projectionMatrix.identity().perspective(this.fov, this.aspectRatio, this.near, this.far);
      return this.viewMatrix.identity().lookAt(this.position, this.target, this.up);
    };

    Camera.prototype.getViewMatrix = function() {
      return this.viewMatrix;
    };

    Camera.prototype.getProjectionMatrix = function() {
      return this.projectionMatrix;
    };

    Camera.prototype.lookAt = function(target, eyePosition, up) {
      if (target) {
        this.target = target;
      }
      if (eyePosition) {
        this.position = eyePosition;
      }
      if (up) {
        this.up = up;
      }
      return this.updateMatrices();
    };

    return Camera;

  })();
});
