// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Scene;

  return Scene = (function() {
    function Scene() {}

    Scene.prototype.draw = function() {};

    return Scene;

  })();
});
